### ISSUE TITLE
Excluded object, still included

### ISSUE THREAD

**Issue by Gompje** [bpineau/katafygio#75]
I'm getting a new commit every time the releasetime of the cert manager changes:

```yaml
kind: ConfigMap
metadata:
  annotations:
    control-plane.alpha.kubernetes.io/leader: '{
"holderIdentity":"certmanager-cert-manager-7887d685f5-6qcrc-external-cert-manager-controller", 
"leaseDurationSeconds":60,
"acquireTime":"2019-05-22T16:04:21Z",
"renewTime":"2019-05-24T22:39:24Z",
"leaderTransitions":0}'
     name: cert-manager-controller
  namespace: gitlab-managed-apps
```
new commit when this timestamp changed:

```yaml
... "renewTime":"2019-05-24T22:39:39Z"
```

This is my config:

```yaml
# excludeKind is an array of excluded (not backuped) Kubernetes objects kinds.
excludeKind:
  - replicaset
  - endpoints
  - event
  - node
  - secret
  - pod
  - lease

# excludeObject is an array of specific Kubernetes objects to exclude from dumps
# (the format is: objectkind:namespace/objectname).
excludeObject:
  - "configmap:kube-system/leader-elector"
  - "configmap:gitlab-managed-apps/configmap-cert-manager-controller"
  - "configmap:gitlab-managed-apps/configmap-ingress-controller-leader-nginx"
```

I've installed the app with rancher and the helm chart in the repository.  Shouldn't this file be excluded given I listed it in the excludeObject array? Or did I mis something? 

I tried changing the case, the rsync interval time to no avail. Help?
