### ISSUE TITLE
CrashLoopBack with error code 2 and no error message

### ISSUE THREAD

**Issue by fredleger** [bpineau/katafygio#81]
**Context:**
- In a kube cluster deployed on AWS via kops.
- installed from official helm charts catalog
- backuping to a gitlab private repo accedded with a non-expiring token
- work for a few weeks and start to crash

Any idea of what could be the cause ?

**Comment by bpineau** [comment]
Could it be hitting the resources limits?
Have a look at `kubectl get pod $katafygiopod -o yaml` status: it will display the last restart's cause.

**Comment by fredleger** [comment]
Hi @bpineau 

It seemes that ressources is not the point here. The only thing showing in the status is an exit with status code 2 : 

```yaml
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2019-07-11T09:39:02Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2019-07-11T09:39:02Z"
    message: 'containers with unready status: [katafygio]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2019-07-11T09:39:02Z"
    message: 'containers with unready status: [katafygio]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2019-07-11T09:39:02Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://ca73ca13dffcfe72b1e2ce86719b590623aed33364cc0b9f8b8678941a5f72eb
    image: bpineau/katafygio:v0.7.1
    imageID: docker-pullable://bpineau/katafygio@sha256:76edd9d121b86c1a079ff118de241984c024e6f3603ccd15089c382f9aed9444
    lastState:
      terminated:
        containerID: docker://ca73ca13dffcfe72b1e2ce86719b590623aed33364cc0b9f8b8678941a5f72eb
        exitCode: 2
        finishedAt: "2019-07-15T10:29:56Z"
        reason: Error
        startedAt: "2019-07-15T10:29:26Z"
    name: katafygio
    ready: false
    restartCount: 1923
    state:
      waiting:
        message: Back-off 5m0s restarting failed container=katafygio pod=katafygio-67984d9d57-844ht_katafygio(b7748dd3-a3bf-11e9-9092-06d4f35fb5ea)
        reason: CrashLoopBackOff
  hostIP: 172.20.39.249
  phase: Running
  podIP: 100.96.2.160
  qosClass: BestEffort
  startTime: "2019-07-11T09:39:02Z"
```

Other pods / helm charts on the cluster are deploying just fine.
